# Generated by Django 5.1.6 on 2025-02-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='question',
        ),
    ]
