# Generated by Django 5.1.6 on 2025-03-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0004_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-added']},
        ),
    ]
