# Generated by Django 5.1.6 on 2025-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0006_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('York', 'York'), ('MC', 'Minecraft'), ('Musc', 'Music')], default='York', max_length=4),
        ),
    ]
