# Generated by Django 5.1.6 on 2025-04-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('york', '0008_blog_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'post'},
        ),
    ]
